# version = "1.0"

[spec.defaults]
# source = { lang = "en" }
target = {
    # langs = ["zh"], # target.langs不能为空，且不可包含source.lang
    use_github_token = false, # default: true
}
# translate = { provider = "deepseek-reasoner" }
deploy = {
    # target = "target",
    source_lang = true, # default: false
}

[spec.runner]
# exec_env = "github_actions"
# cron = "*/5 * * * *"
# tz = "Asia/Shanghai"
# use_secrets = ["", ""]

# Zola
[spec.sites.zola]
meta = {
    desc = "Zola文档翻译",
}
source = {
    git = "https://github.com/getzola/zola.git",
    dir = "docs", # default: ""
    # lang = "en",
}
target = {
    git = "https://github.com/czy-29/docs.29bot.com.git",
    dir = "zola", # default: ""
    # langs = ["zh"],
    # use_github_token = false,
}
framework = {
    preset = "zola",
}
translate = {
    # exts = ["md"], # 不能为空，且不可包含空字符串
    # provider = "deepseek-reasoner",
}
deploy = {
    # target = "target",
    # source_lang = true,
}

# mdBook
[spec.sites.mdbook]
meta = {
    desc = "mdBook文档翻译",
}
source = {
    git = "https://github.com/rust-lang/mdBook.git",
    dir = "guide",
    # lang = "en",
}
target = {
    git = "https://github.com/czy-29/docs.29bot.com.git",
    dir = "mdbook",
    # langs = ["zh"],
    # use_github_token = false,
}
framework = {
    preset = "mdbook",
}
translate = {
    # exts = ["md"],
    # provider = "deepseek-reasoner",
}
deploy = {
    # target = "target",
    # source_lang = true,
}
