# version = "1.0"

[spec.defaults]
# translate = { provider = "deepseek" }
deploy = {
    # target = "target",
    source_lang = true, # default: false
}

[spec.runner]
# exec_env = "github_actions"
# cron = "*/5 * * * *"
# tz = "Asia/Shanghai"
# use_secrets = ["", ""]

# Zola
[spec.sites.zola]
meta = {
    desc = "Zola文档翻译",
}
source = {
    git = "https://github.com/getzola/zola.git",
    dir = "docs", # default: ""
    # lang = "en",
}
target = {
    git = "https://github.com/czy-29/docs.29bot.com.git",
    dir = "zola", # default: ""
    # lang = "zh",
    # use_github_token = true,
}
framework = {
    preset = "zola",
}
translate = {
    # exts = ["md"],
    # provider = "deepseek",
}
deploy = {
    # target = "target",
    # source_lang = true,
}

# mdBook
[spec.sites.mdbook]
meta = {
    desc = "mdBook文档翻译",
}
source = {
    git = "https://github.com/rust-lang/mdBook.git",
    dir = "guide",
    # lang = "en",
}
target = {
    git = "https://github.com/czy-29/docs.29bot.com.git",
    dir = "mdbook",
    # lang = "zh",
    # use_github_token = true,
}
framework = {
    preset = "mdbook",
}
translate = {
    # exts = ["md"],
    # provider = "deepseek",
}
deploy = {
    # target = "target",
    # source_lang = true,
}
